{
 "title": "21. Atlas atvdetails overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ATV general",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(arch,'no_data') as 'Architecture',\nifnull(productmodel,'nodata') as 'Productmodel',\nifnull(MITMSh,'no_data') as 'atlas.sh',\nifnull(55MITM,'no_data') as '55atlas',\nifnull(whversion,'no_data') as 'wh_sender',\nifnull(monitor,'no_data') as 'monitor',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY arch,productmodel,MITMSh,55MITM,whversion,monitor\n"
    }
   ]
  },
  {
   "title": "Magisk / modules",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(magisk,'no_data') as 'Magisk',\nifnull(magisk_modules,'no_data') as 'Modules loaded',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY magisk, magisk_modules\n"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(pogo,'no_data') as 'PoGo',\nifnull(MITMsh,'no_data') as 'Atlas',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY pogo,MITMsh\n"
    }
   ]
  },
  {
   "title": "Atlas settings",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(rdmUrl, 'no_data') as 'rdmUrl',\nifnull(authBearer, 'no_data') as 'authBearer',\nifnull(token, 'no_data') as 'deviceAuthToken',\nifnull(email, 'no_data') as 'email',\nifnull(onBoot, 'no_data') as 'runOnBoot',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY rdmUrl,authBearer,token,email,onBoot"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\nmin(temperature) as 'minTemp',\navg(temperature) as 'avgTemp',\nmax(temperature) as 'maxTemp'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day"
    }
   ]
  },
  {
   "title": "Temperature (Top 5)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\ndeviceName,\nTemperature\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\norder by temperature DESC\nlimit 5\n"
    }
   ]
  },
  {
   "title": "Temperature (Lowest 5)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\ndeviceName,\nTemperature\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\norder by temperature ASC\nlimit 5\n"
    }
   ]
  }
 ]
}