#!/system/bin/sh
# version 1.2

#Create logfile
if [ ! -e /sdcard/aconf.log ] ;then
    touch /sdcard/aconf.log
fi
echo "" >> /sdcard/aconf.log
echo "`date +%Y-%m-%d_%T` Device rebooted" >> /sdcard/aconf.log

# execute atlas.sh
cd /data/local/tmp/cos && setsid nohup ./com.nianticlabs.pokemongo >/dev/null 2>&1 &
